# **L1 & L2 Regularisation : -**

In [93]:
import pandas as pd 
import numpy as np 
import matplotlib as mlt

In [94]:
df = pd.read_csv('/Users/yuvrajbhatkariya/Downloads/Practice_Datset/MELBOURNE_HOUSE_PRICES_LESS.csv')                                                                          
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3,h,1515000.0,S,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2,h,670000.0,S,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63018,Roxburgh Park,3 Carr Pl,3,h,566000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63019,Roxburgh Park,9 Parker Ct,3,h,500000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63020,Roxburgh Park,5 Parkinson Wy,3,h,545000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63021,Thomastown,3/1 Travers St,3,u,NaN,PI,Barry,31/03/2018,3074,Northern Metropolitan,7955,15.3,Whittlesea City Council
63022,Williams Landing,1 Diadem Wy,4,h,NaN,SP,Aussie,31/03/2018,3027,Western Metropolitan,1999,17.6,Wyndham City Council

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63023 entries, 0 to 63022
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         63023 non-null  object
 1   Address        63023 non-null  object
 2   Rooms          63023 non-null  int64
 3   Type           63023 non-null  object
 4   Price          48433 non-null  float64
 5   Method         63023 non-null  object
 6   SellerG        63023 non-null  object
 7   Date           63023 non-null  object
 8   Postcode       63023 non-null  int64
 9   Regionname     63023 non-null  object
 10  Propertycount  63023 non-null  int64
 11  Distance       63023 non-null  float64
 12  CouncilArea    63023 non-null  object
dtypes: float64(2), int64(3), object(8)
memory usage: 6.3+ MB

In [96]:
df.isnull().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price            14590
Method               0
SellerG              0
Date                 0
Postcode             0
Regionname           0
Propertycount        0
Distance             0
CouncilArea          0
dtype: int64

In [97]:
df = df.dropna(subset = ['Price'])
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3,h,1515000.0,S,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2,h,670000.0,S,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council

In [98]:
df.isnull().sum()

Suburb           0
Address          0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Date             0
Postcode         0
Regionname       0
Propertycount    0
Distance         0
CouncilArea      0
dtype: int64

# **One Hot Encoding : -**

In [99]:
from sklearn.preprocessing import OneHotEncoder
df = pd.get_dummies(df,columns = ['Type','Method'],drop_first = True)
df.head()

,Suburb,Address,Rooms,Price,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea,Type_t,Type_u,Method_S,Method_SA,Method_SP,Method_VB
0,Abbotsford,49 Lithgow St,3,1490000.0,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council,False,False,True,False,False,False
1,Abbotsford,59A Turner St,3,1220000.0,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council,False,False,True,False,False,False
2,Abbotsford,119B Yarra St,3,1420000.0,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council,False,False,True,False,False,False
3,Aberfeldie,68 Vida St,3,1515000.0,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council,False,False,True,False,False,False
4,Airport West,92 Clydesdale Rd,2,670000.0,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council,False,False,True,False,False,False

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 48433 entries, 0 to 63020
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         48433 non-null  object
 1   Address        48433 non-null  object
 2   Rooms          48433 non-null  int64
 3   Price          48433 non-null  float64
 4   SellerG        48433 non-null  object
 5   Date           48433 non-null  object
 6   Postcode       48433 non-null  int64
 7   Regionname     48433 non-null  object
 8   Propertycount  48433 non-null  int64
 9   Distance       48433 non-null  float64
 10  CouncilArea    48433 non-null  object
 11  Type_t         48433 non-null  bool
 12  Type_u         48433 non-null  bool
 13  Method_S       48433 non-null  bool
 14  Method_SA      48433 non-null  bool
 15  Method_SP      48433 non-null  bool
 16  Method_VB      48433 non-null  bool
dtypes: bool(6), float64(2), int64(3), object(6)
memory usage: 4.7+ MB

# **Label Encoding : -**

In [101]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
col = ['Suburb','Address','SellerG','Date','Regionname','CouncilArea']
for i in col:
    df[i] = le.fit_transform(df[i])
df.head()

,Suburb,Address,Rooms,Price,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea,Type_t,Type_u,Method_S,Method_SA,Method_SP,Method_VB
0,0,32929,3,1490000.0,180,0,3067,2,4019,3.0,32,False,False,True,False,False,False
1,0,36347,3,1220000.0,225,0,3067,2,4019,3.0,32,False,False,True,False,False,False
2,0,6375,3,1420000.0,253,0,3067,2,4019,3.0,32,False,False,True,False,False,False
3,1,38887,3,1515000.0,28,0,3040,6,1543,7.5,22,False,False,True,False,False,False
4,2,44313,2,670000.0,253,0,3042,6,3464,10.4,22,False,False,True,False,False,False

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 48433 entries, 0 to 63020
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         48433 non-null  int64
 1   Address        48433 non-null  int64
 2   Rooms          48433 non-null  int64
 3   Price          48433 non-null  float64
 4   SellerG        48433 non-null  int64
 5   Date           48433 non-null  int64
 6   Postcode       48433 non-null  int64
 7   Regionname     48433 non-null  int64
 8   Propertycount  48433 non-null  int64
 9   Distance       48433 non-null  float64
 10  CouncilArea    48433 non-null  int64
 11  Type_t         48433 non-null  bool
 12  Type_u         48433 non-null  bool
 13  Method_S       48433 non-null  bool
 14  Method_SA      48433 non-null  bool
 15  Method_SP      48433 non-null  bool
 16  Method_VB      48433 non-null  bool
dtypes: bool(6), float64(2), int64(9)
memory usage: 4.7 MB

In [103]:
df['SellerG'].unique()
df['Distance'].max()

np.float64(55.8)

# **Normalization: -**

In [104]:
# from sklearn.preprocessing import StandardScaler
# col = ['Address','Postcode','Propertycount','SellerG']
# sd = StandardScaler()
# for i in col :
#     df[[i]] = sd.fit_transform(df[[i]])
# df.head()

# **Model: -**

In [105]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
kf = KFold(n_splits = 8)
LR = LinearRegression()

In [106]:
X = df.drop('Price',axis = 1)
Y = df['Price']

In [107]:
cross_val_score(LR,X,Y)

array([0.41296418, 0.41489761, 0.41899418, 0.41458224, 0.37757028])

In [108]:
x_train,x_test,y_train, y_test = train_test_split(X,Y,test_size = 0.3,random_state=42)
LR.fit(x_train,y_train)

y_pred = LR.predict(x_test)
r2 = r2_score(y_test,y_pred)
r2

0.4200715065846554

In [109]:
y_pred = LR.predict(x_train)
r2_score(y_train,y_pred)

0.40287479520048797

### **L1 Regularization(using Lasso) : -**

In [110]:
from sklearn import linear_model
lasso_reg = linear_model.Lasso(alpha = 50, max_iter = 100,tol = 0.1)
lasso_reg.fit(x_train ,y_train )

Lasso(alpha=50, max_iter=100, tol=0.1)

In [111]:
lasso_reg.score(x_test,y_test)

0.42008453325602135

In [112]:
lasso_reg.score(x_train,y_train)

0.40287354974800127

### **L2 Rgularization: -(using Ridge)**

In [113]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha = 100,max_iter=1000,tol = 0.01)
ridge_reg.fit(x_train,y_train)

Ridge(alpha=100, max_iter=1000, tol=0.01)

In [114]:
ridge_reg.score(x_test,y_test)

0.4201632526044551

In [115]:
ridge_reg.score(x_train,y_train)

0.4028389219445663