In [1]:
import pandas as pd

In [20]:
# import kagglehub
# # Download latest version
# path = kagglehub.dataset_download("lakshmi25npathi/imdb-dataset-of-50k-movie-reviews")
# print("Path to dataset files:", path)

In [21]:
df = pd.read_csv("IMDB Dataset.csv")
df.sample(5)

                                                  review sentiment
34468  The arrival of White Men in Arctic Canada chal...  positive
24047  I can't say this is the worst film of all time...  negative
49637  If you liked the Richard Chamberlain version o...  positive
36260  Probably because this is Columbia's first film...  positive
15427  Okay. Look- I've seen LOTS and I do mean LOTS ...  negative

In [22]:
df['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [23]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [24]:
df['sentiment'] =df['sentiment'].apply(lambda x: 0 if x=='positive' else 1)
df.sample(5)

                                                  review  sentiment
43291  The Lion King 1 1/2 is a very cute story to go...          0
28005  After being bitten by a bat in a cave,a doctor...          1
949    The film someone had to make.<br /><br />Waco:...          0
17125  This is superb - the acting wonderful, sets, c...          0
14367  Some films just fade away, but Tourist Trap ha...          0

In [25]:
from  sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df.review ,df.sentiment,test_size=0.20)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)

(40000,)
(10000,)
(40000,)

In [26]:
X_train.values[0:2]

array(['Totally forgettable movie but an unbelievable soundtrack: I\'d give it (soundtrack)a 9 out of 10. I have the CD and the guitar work (Nils Lofgren) is superb! I saw the movie years ago and had to check IMDb to remember what it was about. I obsessed about getting the soundtrack and have since had to replace it. It ranges from blues/soul/ballad to a dose of gospel. All songs written, arranged, produced and performed by Nils Lofgren who is the "other" lead guitarist opposite Steve Van Zandt in the E Street Band. This dude can play! The vocals are handled by Nils (he can\'t sing very good-too raspy), Bonnie Sheridan (who is a great singer) and Tom Lepson.',
       'Coinciding with the start of the baby boom, the years after World War II saw an unprecedented exodus of Americans moving out of their city apartments into the suburbs where they can fulfill their dreams of owning their own homes. Directed by H.C. Potter and co-written by Norman Panama and Melvin Frank ("White Christmas"), this lightweight but surprisingly observant 1948 screwball comedy captures the feeling of that period very well. Of course, it helps to have a trio of expert farceurs \x96 Cary Grant, Myrna Loy and an especially acerbic Melvyn Douglas \x96 head the proceedings with their natural likability at odds with the escalating frustrations of home ownership. Even though the film is sixty years old now, there is a timeless quality to the Blandings\' dream and the barriers they face in achieving it. Obviously, Hollywood thinks so since it\'s been remade at least twice - first as a very physical Tom Hanks comedy, 1986\'s "The Money Pit", and again last year with Ice Cube\'s "Are We Done Yet?". One look at HGTV\'s programming schedule will show you how the situations explored here still resonate today.<br /><br />The plot begins with ad man Jim Blandings, his wife Muriel and their two daughters cramped into a two bedroom-one bath Manhattan apartment. Rather than pursue Muriel\'s idea to renovate the apartment for $7,000, Jim sees a photo of a Connecticut house in a magazine and realizes this is where they need to move. With the help of an opportunistic real estate agent and against the advice of their attorney and family friend Bill Cole, the Blandings decide to buy a ramshackle house badly in need of repair. However, the foundation sags so badly that the house needs to be torn down in favor of a new one. This sparks the Blandings to push the architect to design a house so excessive that the second floor is twice as big as the first. Costs rise with each new complication, tempers flare, and even a romantic triangle is imagined among, Jim, Muriel and Bill. Priorities finally sort themselves out but not before some funny slapstick scenes and clever dialogue that tweaks the not-so-blissful ignorance of the new homeowners.<br /><br />With his double takes and flawless line delivery, Grant is infallible in this type of farce, and Jim Blandings epitomizes his more domesticated mid-career characters. In a role originally meant for Irene Dunne, Myrna Loy shows why she was Hollywood\'s perfect wife. She doesn\'t get many of the funnier lines, but she combines her special blend of flightiness and sauciness to make Muriel an appealing character on her own. Watch her deftly maneuver the overly agreeable house painter with her absurdly idiosyncratic color palette. As avuncular, pipe-smoking Bill ("Cole\x85Bill Cole"), Melvyn Douglas shows his natural, easy-going élan as Grant\'s foil. Smaller roles are filled expertly with particularly memorable turns by Harry Shannon as the laconic well-digger Mr. Tesander, Lurene Tuttle as Jim\'s officious assistant Mary, and Louise Beavers as the Blandings\' lovable maid Gussie. The 2004 DVD provides some intriguing vintage material including two radio versions of the movie - the first a 1949 version that did end up pairing Grant and Dunne and then a second 1950 version coupling Grant with his then-wife, actress Betsy Drake. A most appropriate 1949 cartoon, "The House of Tomorrow", is also included giving us a comical tour of a futuristic dream house. The original theatrical trailers for ten of Grant\'s film classics complete the extras.'],
      dtype=object)

In [27]:
type(X_train)

pandas.core.series.Series

In [28]:
X_train

23541    Totally forgettable movie but an unbelievable ...
34414    Coinciding with the start of the baby boom, th...
26908    This movie which was released directly on vide...
7878     Bad sequels.....this one's a real one! When th...
4905     I fell asleep on my couch at 7:35pm last night...
                               ...
20626    Absolutely amazing! Humor, up-beat music and a...
35289    Watching this again recently, I found it heart...
49254    As interesting as a sheet of cardboard, this d...
4848     Ok first of all, this movie sucks. But lets ex...
18490    I was surprised how much I enjoyed this. Sure ...
Name: review, Length: 40000, dtype: object

### **Bag of words : -**

In [29]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

x_train_cv = v.fit_transform(X_train.values)
x_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 5460248 stored elements and shape (40000, 92744)>

In [30]:
x_train = x_train_cv.toarray()

In [31]:
x_train[0:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(3, 92744))

In [32]:
v.get_feature_names_out()

array(['00', '000', '00000000000', ..., 'ýs', 'þór', 'żmijewski'],
      shape=(92744,), dtype=object)

In [33]:
X_train.values

array(['Totally forgettable movie but an unbelievable soundtrack: I\'d give it (soundtrack)a 9 out of 10. I have the CD and the guitar work (Nils Lofgren) is superb! I saw the movie years ago and had to check IMDb to remember what it was about. I obsessed about getting the soundtrack and have since had to replace it. It ranges from blues/soul/ballad to a dose of gospel. All songs written, arranged, produced and performed by Nils Lofgren who is the "other" lead guitarist opposite Steve Van Zandt in the E Street Band. This dude can play! The vocals are handled by Nils (he can\'t sing very good-too raspy), Bonnie Sheridan (who is a great singer) and Tom Lepson.',
       'Coinciding with the start of the baby boom, the years after World War II saw an unprecedented exodus of Americans moving out of their city apartments into the suburbs where they can fulfill their dreams of owning their own homes. Directed by H.C. Potter and co-written by Norman Panama and Melvin Frank ("White Christmas"), this lightweight but surprisingly observant 1948 screwball comedy captures the feeling of that period very well. Of course, it helps to have a trio of expert farceurs \x96 Cary Grant, Myrna Loy and an especially acerbic Melvyn Douglas \x96 head the proceedings with their natural likability at odds with the escalating frustrations of home ownership. Even though the film is sixty years old now, there is a timeless quality to the Blandings\' dream and the barriers they face in achieving it. Obviously, Hollywood thinks so since it\'s been remade at least twice - first as a very physical Tom Hanks comedy, 1986\'s "The Money Pit", and again last year with Ice Cube\'s "Are We Done Yet?". One look at HGTV\'s programming schedule will show you how the situations explored here still resonate today.<br /><br />The plot begins with ad man Jim Blandings, his wife Muriel and their two daughters cramped into a two bedroom-one bath Manhattan apartment. Rather than pursue Muriel\'s idea to renovate the apartment for $7,000, Jim sees a photo of a Connecticut house in a magazine and realizes this is where they need to move. With the help of an opportunistic real estate agent and against the advice of their attorney and family friend Bill Cole, the Blandings decide to buy a ramshackle house badly in need of repair. However, the foundation sags so badly that the house needs to be torn down in favor of a new one. This sparks the Blandings to push the architect to design a house so excessive that the second floor is twice as big as the first. Costs rise with each new complication, tempers flare, and even a romantic triangle is imagined among, Jim, Muriel and Bill. Priorities finally sort themselves out but not before some funny slapstick scenes and clever dialogue that tweaks the not-so-blissful ignorance of the new homeowners.<br /><br />With his double takes and flawless line delivery, Grant is infallible in this type of farce, and Jim Blandings epitomizes his more domesticated mid-career characters. In a role originally meant for Irene Dunne, Myrna Loy shows why she was Hollywood\'s perfect wife. She doesn\'t get many of the funnier lines, but she combines her special blend of flightiness and sauciness to make Muriel an appealing character on her own. Watch her deftly maneuver the overly agreeable house painter with her absurdly idiosyncratic color palette. As avuncular, pipe-smoking Bill ("Cole\x85Bill Cole"), Melvyn Douglas shows his natural, easy-going élan as Grant\'s foil. Smaller roles are filled expertly with particularly memorable turns by Harry Shannon as the laconic well-digger Mr. Tesander, Lurene Tuttle as Jim\'s officious assistant Mary, and Louise Beavers as the Blandings\' lovable maid Gussie. The 2004 DVD provides some intriguing vintage material including two radio versions of the movie - the first a 1949 version that did end up pairing Grant and Dunne and then a second 1950 version coupling Grant with his then-wife, actress Betsy Drake. A most appropriate 1949 cartoon, "The House of Tomorrow", is also included giving us a comical tour of a futuristic dream house. The original theatrical trailers for ten of Grant\'s film classics complete the extras.',
       'This movie which was released directly on video should carry a warning label that it is dangerous to human health and may subject the viewer to terminal boredom. It is yet another thinly veiled, evangalizing "rapture" religious movie with the good guys (the believers) suddenly vanishing and the bad guys (the non-believers)left behind. It\'s an interesting concept, especially since we see it happen on a flight captained by a non-believer who is having a sinful affair with a stewardess aboard (needless to say that sinner doesn\'t disappear either!). Unhappily, with all the pilots being non-believers, the plane did not crash or the movie would have been mercifully over. Though this could have be interesting without the heavy religious browbeating, as a whole the plodding movie makes one gag, the acting is horrible and the obviously computer-generated simulations are very fake looking. Plus it\'s yet another movie shot in Canada that purports to be New York City. Spare me...I\'ll just read the Bible.',
       ...,
       "As interesting as a sheet of cardboard, this dispensable period piece has little going for it. It's overly wordy and fails spectacularly to evoke the tension and fear that the real-life characters must have felt as they dodged the French Revolution's fickle hand of justice. Eric Rohmer at 82? It shows.",
       "Ok first of all, this movie sucks. But lets examine why. The proposition that a machine is capable of transforming matter into energy, storing it, and then transporting it and reasembling it is at the least intriguing. But that's as far as they take this premise. Instead of delving into what could happen if someone made this kind of machine, they break the damn thing. This could have been a good premise. Living with the responsibilty of this kind of power, and dealing with the constant temptation, ie.. the invisible man. But no.. they break the damn thing. And Lembach wants to leave. So then the doctor jerry-rigs the thing back together, and trys to transport himself. Only to have it goofed up by his beautiful but dumb secretary, (duh). Which wouldn't happened if Lembach hadn't decided to leave. So now he is roaming the country side killing people because his little experiment failed, and they wouldn't give him money. Wah. Then to make the movie worse, throw in a dry British relationship between the two semi-competent professors hired to assist him. Between their loving sessions, they make a couple of half-hearted attempts to find him while he kills off half of London. All of this could have been headed off by not breaking the damn machine, which would never have happened if Lembach hadn't left. This movie tried so I give it an honest 2 stars for effort, but it would have been better if they hadn't broke the damn machine, making Lembach leave, making him try it again. Damn you Lembach!!!!!!!!!!!!!!!!",
       "I was surprised how much I enjoyed this. Sure it is a bit slow moving in parts, but what else would one expect from Rollin? Also there is plenty of nudity, nothing wrong with that, particularly as it includes lots of the gorgeous, Brigitte Lahaie. There are also some spectacularly eroticised female dead, bit more dodgey, perhaps, but most effective. There is also a sci-fi like storyline with a brief explanation at the end, but I wouldn't bother too much with that. No, here we have a most interesting exploration of memory and the effect of memory loss and to just what extent one is still 'alive' without memory. My DVD sleeve mentions David Cronenberg and whilst this is perhaps not quite as good as his best films, there is some similarity here, particularly with the great use of seemingly menacing architecture and the effective and creepy use of inside space. As I have tried to indicate this is by no means a rip roaring thriller, it is a captivating, nightmare like movie that makes the very most of its locations, including a stunning railway setting at the end."],
      shape=(40000,), dtype=object)

In [35]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.naive_bayes import MultinomialNB

# Define stratified CV with random shuffling
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# Hyperparameters to tune
param_grid = {
    "alpha": [0.01, 0.8, 0.5, 0.6,0.7,0.9,1, 2, 5],
    "fit_prior": [True, False]
}

# Model
nb = MultinomialNB()

# GridSearchCV
grid = GridSearchCV(
    estimator=nb,
    param_grid=param_grid,
    cv=cv,
    scoring="f1",
    n_jobs=-1,
    verbose=1
)

# Fit
grid.fit(x_train_cv, y_train)

# Results
print("Best Parameters:", grid.best_params_)
print("Best F1 Score:", grid.best_score_)

Fitting 5 folds for each of 18 candidates, totalling 90 fits
Best Parameters: {'alpha': 0.8, 'fit_prior': True}
Best F1 Score: 0.8519601831188846

In [39]:
from sklearn.naive_bayes import MultinomialNB

# 🔹 Put YOUR parameters here
model = MultinomialNB(
    alpha=0.8,        
    fit_prior=False    
)

# 🔹 Train the model
model.fit(x_train_cv, y_train)

MultinomialNB(alpha=0.8, fit_prior=False)

In [40]:
x_test_cv = v.transform(X_test)
x_test_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 1356528 stored elements and shape (10000, 92744)>

In [41]:
x_test = x_test_cv.toarray()
x_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(10000, 92744))

In [42]:
from sklearn.metrics import classification_report
y_pred = model.predict(x_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.88      0.82      0.85      5028
           1       0.83      0.88      0.86      4972

    accuracy                           0.85     10000
   macro avg       0.86      0.85      0.85     10000
weighted avg       0.86      0.85      0.85     10000