In [1]:
import pandas as pd
import numpy as np
print ('HELLO VEDNESDAY')

HELLO VEDNESDAY

In [2]:
A = np.arange(1,21).reshape(4,5)

In [3]:
#  creating a DataFrameWork :-

new = pd.DataFrame(data = A,index = ["Row1","Row2","Row3","Row4"],
             columns = ["Columns1","Columns2","Columns3","Columns4","Columns5"] )

In [4]:
new.head(3)
new.tail(3)

      Columns1  Columns2  Columns3  Columns4  Columns5
Row2         6         7         8         9        10
Row3        11        12        13        14        15
Row4        16        17        18        19        20

In [5]:
type(new)
new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Row1 to Row4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Columns1  4 non-null      int32
 1   Columns2  4 non-null      int32
 2   Columns3  4 non-null      int32
 3   Columns4  4 non-null      int32
 4   Columns5  4 non-null      int32
dtypes: int32(5)
memory usage: 112.0+ bytes

In [6]:
new.describe()

        Columns1   Columns2   Columns3   Columns4   Columns5
count   4.000000   4.000000   4.000000   4.000000   4.000000
mean    8.500000   9.500000  10.500000  11.500000  12.500000
std     6.454972   6.454972   6.454972   6.454972   6.454972
min     1.000000   2.000000   3.000000   4.000000   5.000000
25%     4.750000   5.750000   6.750000   7.750000   8.750000
50%     8.500000   9.500000  10.500000  11.500000  12.500000
75%    12.250000  13.250000  14.250000  15.250000  16.250000
max    16.000000  17.000000  18.000000  19.000000  20.000000

In [7]:
# INDEXING : -
#  1. by column name:
new['Columns1']                  # it is series type
new[['Columns2','Columns3']]     # is dataftame

      Columns2  Columns3
Row1         2         3
Row2         7         8
Row3        12        13
Row4        17        18

In [8]:
# 2. by row index: -
new.loc[['Row4','Row3']] 
new

      Columns1  Columns2  Columns3  Columns4  Columns5
Row1         1         2         3         4         5
Row2         6         7         8         9        10
Row3        11        12        13        14        15
Row4        16        17        18        19        20

In [9]:
# 3.by iloc
new.iloc[2:3,0:4]

      Columns1  Columns2  Columns3  Columns4
Row3        11        12        13        14

In [10]:
# convert dataframe into array format
new.iloc[ : , 2:].values

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [11]:
#  Creating a new data frame havinf nan value :-)
df = pd.DataFrame(data = [[1,np.nan,2],[1,2,3]],index = ["Row1","Row2"],
             columns = ["Columns1","Columns2","Columns3"] )
df

      Columns1  Columns2  Columns3
Row1         1       NaN         2
Row2         1       2.0         3

In [12]:
df.isnull()

      Columns1  Columns2  Columns3
Row1     False      True     False
Row2     False     False     False

In [13]:
df.isnull().sum()

Columns1    0
Columns2    1
Columns3    0
dtype: int64

In [14]:
df

      Columns1  Columns2  Columns3
Row1         1       NaN         2
Row2         1       2.0         3

In [15]:
df['Columns3'].value_counts()

Columns3
2    1
3    1
Name: count, dtype: int64

In [16]:
df['Columns3'].unique()

array([2, 3], dtype=int64)

In [17]:
new

      Columns1  Columns2  Columns3  Columns4  Columns5
Row1         1         2         3         4         5
Row2         6         7         8         9        10
Row3        11        12        13        14        15
Row4        16        17        18        19        20

In [18]:
new[new['Columns3']>3]

      Columns1  Columns2  Columns3  Columns4  Columns5
Row2         6         7         8         9        10
Row3        11        12        13        14        15
Row4        16        17        18        19        20