In [14]:
# Pandas using with jason :-)
import pandas as pd
from io import StringIO

In [61]:
data = '{"Employee_name" : "Harry","Email" : "harry@gmail.com", "Job_profile" : [{"Title1" : "Ethecial_Hacker", "Tile2" : "Ai Engineer"}]}'

In [63]:
# Creating a dataframe from string in jason foramt :-
df = pd.read_json(StringIO(data))
df

,Employee_name,Email,Job_profile
0,Harry,harry@gmail.com,"{'Title1': 'Ethecial_Hacker', 'Tile2': 'Ai Eng..."

In [17]:
type(df)

pandas.core.frame.DataFrame

In [18]:
pd.read_json(StringIO(data),orient = 'record')

,Employee_name,Email,Job_profile
0,Harry,harry@gmail.com,"{'Title1': 'Ethecial_Hacker', 'Tile2': 'Ai Eng..."

In [22]:
pd.read_json(StringIO(data),orient = 'index')

                                                               0
Employee_name                                              Harry
Email                                            harry@gmail.com
Job_profile    [{'Title1': 'Ethecial_Hacker', 'Tile2': 'Ai En...

In [24]:
# pd.read_json(StringIO(data),orient = 'split')
pd.read_json(StringIO(data),orient = 'column')

,Employee_name,Email,Job_profile
0,Harry,harry@gmail.com,"{'Title1': 'Ethecial_Hacker', 'Tile2': 'Ai Eng..."

In [32]:
# Cinverting dataframe into json :-
df = pd.DataFrame(data = [['a','b'],['c','d']],index = ["Row1","Row2"],columns =["Column1","Column2"] )
type(df)
df

     Column1 Column2
Row1       a       b
Row2       c       d

In [34]:

df.to_json()      # default it convert into column format :-
df.to_json(orient = 'columns')

'{"Column1":{"Row1":"a","Row2":"c"},"Column2":{"Row1":"b","Row2":"d"}}'

In [33]:
df.to_json(orient = 'index')    # convert into row format:-

'{"Row1":{"Column1":"a","Column2":"b"},"Row2":{"Column1":"c","Column2":"d"}}'

In [35]:
df.to_json(orient  = 'split')  # Seperate everything :-

'{"columns":["Column1","Column2"],"index":["Row1","Row2"],"data":[["a","b"],["c","d"]]}'

In [37]:
df.to_json(orient = 'table')     # give all details :-

'{"schema":{"fields":[{"name":"index","type":"string"},{"name":"Column1","type":"string"},{"name":"Column2","type":"string"}],"primaryKey":["index"],"pandas_version":"1.4.0"},"data":[{"index":"Row1","Column1":"a","Column2":"b"},{"index":"Row2","Column1":"c","Column2":"d"}]}'

In [38]:
da = '{"schema":{"fields":[{"name":"index","type":"string"},{"name":"Column1","type":"string"},{"name":"Column2","type":"string"}],"primaryKey":["index"],"pandas_version":"1.4.0"},"data":[{"index":"Row1","Column1":"a","Column2":"b"},{"index":"Row2","Column1":"c","Column2":"d"}]}'

In [40]:
pd.read_json(StringIO(da),orient = 'table')

     Column1 Column2
Row1       a       b
Row2       c       d

In [51]:
df = pd.read_csv('test.csv')
df.head()

,id,f0,f1,f2,f3,f4,f5,f6,f7,f8,...,f90,f91,f92,f93,f94,f95,f96,f97,f98,f99
0,15000,0.398169,2.14330,114.8780,3.816510,0.089995,1.042540,5.307310,1.767470,1.35030,...,0.040523,1.308520,0.065694,0.047387,-0.035951,0.281766,0.477826,1.62488,0.029438,-0.031790
1,15001,0.008505,2.34932,853.8810,5.231130,0.049947,1.107780,0.928617,0.293212,1.11765,...,0.080400,4.083920,0.047871,0.105594,0.030981,0.096044,3.408660,2.27766,-0.015950,0.093279
2,15002,2.767680,2.08453,148.9250,4.046420,0.007924,4.261860,1.295550,-0.310799,4.30696,...,0.078513,-0.250609,0.029606,0.092942,-0.044077,0.106987,3.987810,1.68461,1.205700,0.106042
3,15003,1.071190,5.91952,-64.0648,0.195529,0.079169,0.903287,4.935910,1.769730,1.76636,...,0.103638,0.938042,0.014003,0.050670,0.114732,0.405016,3.223190,4.58780,0.051759,0.094247
4,15004,0.068140,3.53945,-25.8223,5.739260,0.038304,3.349190,4.220190,1.177650,4.92934,...,0.106432,3.928190,0.700506,0.013716,0.033387,0.057754,3.433780,3.64833,0.076186,0.045207

In [52]:
df.to_json('test.json', orient = 'index')

In [55]:

data = [{"Employee_name" : "Harry","Email" : "harry@gmail.com", "Job_profile" : {"Title1" : "Ethecial_Hacker", "Tile2" : "Ai Engineer"}}]
type(data)

list

In [60]:
pd.json_normalize(data)

  Employee_name            Email Job_profile.Title1 Job_profile.Tile2
0         Harry  harry@gmail.com    Ethecial_Hacker       Ai Engineer

In [65]:
data = [
    {
        "id": 1,
        "name": "Cole Volk",
        "fitness": {"height": 130, "weight": 60},
    },
    {"name": "Mark Reg", "fitness": {"height": 130, "weight": 60}},
    {
        "id": 2,
        "name": "Faye Raker",
        "fitness": {"height": 130, "weight": 60},
    },
]

In [66]:
pd.json_normalize(data)

    id        name  fitness.height  fitness.weight
0  1.0   Cole Volk             130              60
1  NaN    Mark Reg             130              60
2  2.0  Faye Raker             130              60

In [70]:
pd.json_normalize(data,max_level = 0)

    id        name                        fitness
0  1.0   Cole Volk  {'height': 130, 'weight': 60}
1  NaN    Mark Reg  {'height': 130, 'weight': 60}
2  2.0  Faye Raker  {'height': 130, 'weight': 60}

In [69]:
pd.json_normalize(data,max_level = 1)

    id        name  fitness.height  fitness.weight
0  1.0   Cole Volk             130              60
1  NaN    Mark Reg             130              60
2  2.0  Faye Raker             130              60

In [71]:
data = [
    {
        "state": "Florida",
        "shortname": "FL",
        "info": {"governor": "Rick Scott"},
        "counties": [
            {"name": "Dade", "population": 12345},
            {"name": "Broward", "population": 40000},
            {"name": "Palm Beach", "population": 60000},
        ],
    },
    {
        "state": "Ohio",
        "shortname": "OH",
        "info": {"governor": "John Kasich"},
        "counties": [
            {"name": "Summit", "population": 1234},
            {"name": "Cuyahoga", "population": 1337},
        ],
    },
]

In [79]:
pd.json_normalize(data,max_level = 3)

,state,shortname,counties,info.governor
0,Florida,FL,"[{'name': 'Dade', 'population': 12345}, {'name...",Rick Scott
1,Ohio,OH,"[{'name': 'Summit', 'population': 1234}, {'nam...",John Kasich

In [89]:
pd.json_normalize(data,"counties",["state","shortname",["info", "governor"]])

         name  population    state shortname info.governor
0        Dade       12345  Florida        FL    Rick Scott
1     Broward       40000  Florida        FL    Rick Scott
2  Palm Beach       60000  Florida        FL    Rick Scott
3      Summit        1234     Ohio        OH   John Kasich
4    Cuyahoga        1337     Ohio        OH   John Kasich